export const BANK = {
  "School objects": [
    "pencil",
    "eraser",
    "notebook",
    "desk",
    "whiteboard",
    "marker",
    "backpack",
    "ruler",
    "calculator",
    "laptop",
    "dictionary"
  ],
  Hobbies: [
    "painting",
    "gardening",
    "reading",
    "baking",
    "dancing",
    "photography",
    "knitting",
    "camping",
    "birdwatching",
    "yoga",
    "cycling"
  ],
  Food: [
    "pizza",
    "sandwich",
    "pasta",
    "salad",
    "soup",
    "sushi",
    "pancakes",
    "taco",
    "omelet",
    "burger",
    "curry"
  ],
  Places: [
    "library",
    "airport",
    "museum",
    "supermarket",
    "beach",
    "mountain",
    "park",
    "hospital",
    "train station",
    "hotel",
    "stadium"
  ],
  Jobs: [
    "teacher",
    "doctor",
    "chef",
    "engineer",
    "pilot",
    "nurse",
    "farmer",
    "artist",
    "driver",
    "baker",
    "carpenter"
  ],
  Sports: [
    "soccer",
    "basketball",
    "tennis",
    "swimming",
    "volleyball",
    "baseball",
    "running",
    "badminton",
    "table tennis",
    "hiking",
    "skating"
  ],
  Animals: [
    "rabbit",
    "turtle",
    "panda",
    "dolphin",
    "penguin",
    "elephant",
    "giraffe",
    "kangaroo",
    "owl",
    "fox",
    "zebra"
  ],
  Technology: [
    "smartphone",
    "tablet",
    "headphones",
    "camera",
    "smartwatch",
    "printer",
    "keyboard",
    "speaker",
    "router",
    "microphone",
    "charger"
  ],
  "Daily routines": [
    "wake up",
    "brush teeth",
    "eat breakfast",
    "take bus",
    "study",
    "exercise",
    "cook dinner",
    "watch TV",
    "do homework",
    "take shower",
    "go to bed"
  ],
  Weather: [
    "sunny",
    "rainy",
    "cloudy",
    "windy",
    "stormy",
    "snowy",
    "foggy",
    "humid",
    "hot",
    "cold",
    "warm"
  ],
  Travel: [
    "passport",
    "luggage",
    "ticket",
    "map",
    "hotel room",
    "souvenir",
    "tour guide",
    "bus stop",
    "taxi",
    "restaurant",
    "airport gate"
  ]
};
