export const BANK = {
  en: {
    A1: {
      "Everyday items": [
        "book",
        "chair",
        "cup",
        "door",
        "phone",
        "table",
        "spoon",
        "key",
        "shirt",
        "bag"
      ],
      Family: [
        "mother",
        "father",
        "sister",
        "brother",
        "grandmother",
        "grandfather",
        "cousin",
        "aunt",
        "uncle",
        "baby"
      ],
      "Food basics": [
        "bread",
        "apple",
        "milk",
        "rice",
        "cheese",
        "egg",
        "banana",
        "salad",
        "soup",
        "juice"
      ],
      "Places in town": [
        "park",
        "school",
        "bank",
        "supermarket",
        "hospital",
        "bus stop",
        "library",
        "cinema",
        "restaurant",
        "station"
      ],
      Classroom: [
        "pencil",
        "notebook",
        "blackboard",
        "desk",
        "eraser",
        "map",
        "backpack",
        "marker",
        "ruler",
        "glue"
      ],
      "Common verbs": [
        "eat",
        "drink",
        "sleep",
        "read",
        "write",
        "run",
        "speak",
        "listen",
        "sit",
        "stand"
      ],
      "Famous cities": [
        "Paris",
        "London",
        "New York",
        "Tokyo",
        "Sydney",
        "Cairo",
        "Toronto",
        "Berlin",
        "Madrid",
        "Rome"
      ]
    },
    A2: {
      Hobbies: [
        "painting",
        "gardening",
        "cycling",
        "photography",
        "cooking",
        "playing chess",
        "singing",
        "dancing",
        "camping",
        "baking"
      ],
      Weather: [
        "sunny",
        "windy",
        "foggy",
        "stormy",
        "humid",
        "chilly",
        "drizzle",
        "heatwave",
        "snowfall",
        "thunder"
      ],
      "Travel essentials": [
        "passport",
        "luggage",
        "ticket",
        "boarding pass",
        "hotel room",
        "map",
        "souvenir",
        "tour guide",
        "platform",
        "currency"
      ],
      "Daily routines": [
        "wake up",
        "brush teeth",
        "eat breakfast",
        "take the bus",
        "study",
        "cook dinner",
        "exercise",
        "do homework",
        "watch TV",
        "go to bed"
      ],
      "Household items": [
        "lamp",
        "pillow",
        "mirror",
        "sofa",
        "blanket",
        "curtain",
        "toaster",
        "microwave",
        "kettle",
        "sponge"
      ],
      Transportation: [
        "bicycle",
        "subway",
        "tram",
        "motorbike",
        "scooter",
        "ferry",
        "carriage",
        "taxi",
        "seatbelt",
        "platform"
      ],
      "Popular brands": [
        "Nike",
        "Adidas",
        "IKEA",
        "Apple",
        "Samsung",
        "Toyota",
        "Lego",
        "Sony",
        "Zara",
        "Pepsi"
      ]
    },
    B1: {
      Technology: [
        "smartphone",
        "tablet",
        "router",
        "charger",
        "headphones",
        "keyboard",
        "microphone",
        "webcam",
        "cloud storage",
        "battery life"
      ],
      Jobs: [
        "engineer",
        "journalist",
        "nurse",
        "architect",
        "chemist",
        "designer",
        "electrician",
        "accountant",
        "librarian",
        "translator"
      ],
      Health: [
        "headache",
        "sore throat",
        "appointment",
        "medicine",
        "allergy",
        "bandage",
        "thermometer",
        "clinic",
        "exercise plan",
        "first aid"
      ],
      "Outdoor activities": [
        "hiking",
        "kayaking",
        "rock climbing",
        "birdwatching",
        "picnic",
        "trail running",
        "campfire",
        "stargazing",
        "fishing",
        "orienteering"
      ],
      Entertainment: [
        "concert",
        "theater",
        "exhibition",
        "stand-up comedy",
        "musical",
        "festival",
        "documentary",
        "short film",
        "playlist",
        "novel series"
      ],
      Shopping: [
        "receipt",
        "discount",
        "fitting room",
        "cashier",
        "warranty",
        "window shopping",
        "basket",
        "price tag",
        "checkout",
        "gift wrap"
      ],
      "Family movies and shows": [
        "Frozen",
        "Toy Story",
        "Finding Nemo",
        "Coco",
        "The Lion King",
        "Moana",
        "Up",
        "Harry Potter",
        "Spider-Man",
        "Jurassic Park"
      ]
    },
    B2: {
      "Academic subjects": [
        "literature",
        "chemistry",
        "economics",
        "philosophy",
        "anthropology",
        "statistics",
        "architecture",
        "linguistics",
        "geology",
        "sociology"
      ],
      Workplace: [
        "deadline",
        "presentation",
        "promotion",
        "mentorship",
        "coworking space",
        "conference call",
        "performance review",
        "prototype",
        "workload",
        "negotiation"
      ],
      Environment: [
        "recycling",
        "biodiversity",
        "renewable energy",
        "carbon footprint",
        "pollution",
        "compost",
        "wildlife reserve",
        "deforestation",
        "ocean current",
        "greenhouse gas"
      ],
      Media: [
        "headline",
        "opinion piece",
        "interview",
        "broadcast",
        "editorial",
        "press release",
        "viewer rating",
        "podcast",
        "syndication",
        "subscription"
      ],
      "Social issues": [
        "volunteering",
        "housing",
        "immigration",
        "public health",
        "education access",
        "inequality",
        "community center",
        "fundraiser",
        "sustainability",
        "activism"
      ],
      Traditions: [
        "harvest festival",
        "national holiday",
        "wedding toast",
        "folk dance",
        "lantern ceremony",
        "storytelling",
        "costume parade",
        "family reunion",
        "seasonal market",
        "craft fair"
      ],
      "Streaming hits": [
        "Stranger Things",
        "The Crown",
        "Money Heist",
        "The Mandalorian",
        "Breaking Bad",
        "The Office",
        "Better Call Saul",
        "Bridgerton",
        "Game of Thrones",
        "The Last of Us"
      ]
    },
    C1: {
      "Abstract nouns": [
        "resilience",
        "integrity",
        "curiosity",
        "compassion",
        "ambiguity",
        "paradox",
        "intuition",
        "detachment",
        "ambition",
        "gratitude"
      ],
      "Science topics": [
        "genetics",
        "quantum physics",
        "ecosystems",
        "cellular biology",
        "astronomy",
        "neuroscience",
        "thermodynamics",
        "plate tectonics",
        "nanotechnology",
        "evolution"
      ],
      "Art movements": [
        "impressionism",
        "surrealism",
        "cubism",
        "baroque",
        "minimalism",
        "expressionism",
        "futurism",
        "romanticism",
        "pop art",
        "realism"
      ],
      Government: [
        "constitution",
        "parliament",
        "coalition",
        "referendum",
        "diplomacy",
        "legislation",
        "jurisdiction",
        "cabinet",
        "civic duty",
        "ombudsman"
      ],
      Business: [
        "stakeholder",
        "entrepreneurship",
        "market research",
        "brand loyalty",
        "merger",
        "diversification",
        "benchmarking",
        "supply chain",
        "cash flow",
        "innovation hub"
      ],
      "Award-winning films": [
        "Parasite",
        "Nomadland",
        "La La Land",
        "Moonlight",
        "The Shape of Water",
        "Spotlight",
        "Birdman",
        "Argo",
        "12 Years a Slave",
        "The Artist"
      ],
      Emotions: [
        "nostalgia",
        "serenity",
        "anticipation",
        "frustration",
        "awe",
        "contentment",
        "empathy",
        "relief",
        "envy",
        "admiration"
      ]
    },
    C2: {
      Idioms: [
        "break the ice",
        "spill the beans",
        "cut to the chase",
        "beyond the pale",
        "once in a blue moon",
        "the last straw",
        "take it with a grain of salt",
        "on the fence",
        "up in the air",
        "hit the nail on the head"
      ],
      "Philosophy terms": [
        "existentialism",
        "stoicism",
        "dialectic",
        "utilitarianism",
        "epistemology",
        "metaphysics",
        "determinism",
        "phenomenology",
        "teleology",
        "ontology"
      ],
      "Advanced verbs": [
        "scrutinize",
        "extrapolate",
        "elucidate",
        "circumvent",
        "underscore",
        "ameliorate",
        "disseminate",
        "corroborate",
        "differentiate",
        "spearhead"
      ],
      "Legal terms": [
        "jurisprudence",
        "precedent",
        "litigation",
        "arbitration",
        "injunction",
        "testimony",
        "liability",
        "indictment",
        "affidavit",
        "plaintiff"
      ],
      "Rhetorical devices": [
        "analogy",
        "metaphor",
        "hyperbole",
        "alliteration",
        "paradox",
        "euphemism",
        "synecdoche",
        "irony",
        "anaphora",
        "oxymoron"
      ],
      "Specialized fields": [
        "cryptography",
        "astrophysics",
        "epidemiology",
        "linguistic typology",
        "urban planning",
        "biomedical engineering",
        "climatology",
        "oceanography",
        "materials science",
        "ethnomusicology"
      ],
      "Classic screen titles": [
        "Citizen Kane",
        "Casablanca",
        "Rashomon",
        "Metropolis",
        "Seven Samurai",
        "Blade Runner",
        "Spirited Away",
        "Pan's Labyrinth",
        "Schindler's List",
        "A Clockwork Orange"
      ]
    }
  },
  ca: {
    A1: {
      "Objectes quotidians": [
        "llibre",
        "cadira",
        "tassa",
        "porta",
        "telèfon",
        "taula",
        "cullera",
        "clau",
        "samarreta",
        "bossa"
      ],
      Família: [
        "mare",
        "pare",
        "germana",
        "germà",
        "àvia",
        "avi",
        "cosí",
        "cosina",
        "tieta",
        "oncle"
      ],
      "Menjar bàsic": [
        "pa",
        "poma",
        "llet",
        "arròs",
        "formatge",
        "ou",
        "plàtan",
        "amanida",
        "sopa",
        "suc"
      ],
      "Llocs de la ciutat": [
        "parc",
        "escola",
        "banc",
        "supermercat",
        "hospital",
        "parada d'autobús",
        "biblioteca",
        "cinema",
        "restaurant",
        "estació"
      ],
      Aula: [
        "llapis",
        "quadern",
        "pissarra",
        "pupitre",
        "goma",
        "mapa",
        "motxilla",
        "retolador",
        "regla",
        "cola"
      ],
      "Verbs comuns": [
        "menjar",
        "beure",
        "dormir",
        "llegir",
        "escriure",
        "córrer",
        "parlar",
        "escoltar",
        "seure",
        "aixecar-se"
      ]
    },
    A2: {
      Aficions: [
        "pintar",
        "jardineria",
        "anar en bici",
        "fotografia",
        "cuinar",
        "jugar als escacs",
        "cantar",
        "ballar",
        "acampar",
        "pastisseria"
      ],
      Temps: [
        "solejat",
        "ventós",
        "boirós",
        "tempestuós",
        "humit",
        "fred",
        "plugim",
        "calorada",
        "nevada",
        "tro"
      ],
      "Viatge bàsic": [
        "passaport",
        "equipatge",
        "bitllet",
        "targeta d'embarcament",
        "habitació d'hotel",
        "mapa",
        "record",
        "guia turística",
        "andrana",
        "moneda"
      ],
      "Rutines diàries": [
        "despertar-se",
        "rentar-se les dents",
        "esmorzar",
        "agafar l'autobús",
        "estudiar",
        "fer el sopar",
        "fer exercici",
        "fer els deures",
        "mirar la tele",
        "anar a dormir"
      ],
      "Casa i llar": [
        "llum",
        "coixí",
        "mirall",
        "sofà",
        "manta",
        "cortina",
        "torradora",
        "microones",
        "bullidor",
        "esponja"
      ],
      Transport: [
        "bicicleta",
        "metro",
        "tramvia",
        "motocicleta",
        "patinet",
        "ferri",
        "carruatge",
        "taxi",
        "cinturó de seguretat",
        "plataforma"
      ]
    },
    B1: {
      Tecnologia: [
        "telèfon intel·ligent",
        "tauleta",
        "encaminador",
        "carregador",
        "auriculars",
        "teclat",
        "micròfon",
        "càmera web",
        "emmagatzematge al núvol",
        "bateria"
      ],
      Feines: [
        "enginyer",
        "periodista",
        "infermera",
        "arquitecte",
        "químic",
        "dissenyador",
        "electricista",
        "comptable",
        "bibliotecari",
        "traductor"
      ],
      Salut: [
        "mal de cap",
        "mal de coll",
        "cita",
        "medicina",
        "al·lèrgia",
        "benes",
        "termòmetre",
        "clínica",
        "pla d'exercici",
        "primers auxilis"
      ],
      "Activitats a l'aire lliure": [
        "excursionisme",
        "piragüisme",
        "escalada",
        "observació d'ocells",
        "pícnic",
        "córrer per camins",
        "foc de camp",
        "observació d'estels",
        "pesca",
        "orientació"
      ],
      Entreteniment: [
        "concert",
        "teatre",
        "exposició",
        "monòleg còmic",
        "musical",
        "festival",
        "documental",
        "curtmetratge",
        "llista de reproducció",
        "sèrie de novel·les"
      ],
      Compres: [
        "tiquet",
        "descompte",
        "emprovador",
        "caixer",
        "garantia",
        "mirar aparadors",
        "cistella",
        "etiqueta de preu",
        "caixa",
        "embolcall de regal"
      ]
    },
    B2: {
      "Assignatures acadèmiques": [
        "literatura",
        "química",
        "economia",
        "filosofia",
        "antropologia",
        "estadística",
        "arquitectura",
        "lingüística",
        "geologia",
        "sociologia"
      ],
      "Món laboral": [
        "termini",
        "presentació",
        "promoció",
        "mentoria",
        "espai de coworking",
        "trucada de conferència",
        "avaluació",
        "prototip",
        "càrrega de feina",
        "negociació"
      ],
      Medi: [
        "reciclatge",
        "biodiversitat",
        "energia renovable",
        "petjada de carboni",
        "contaminació",
        "compost",
        "reserva natural",
        "desforestació",
        "corrents oceàniques",
        "gasos d'efecte hivernacle"
      ],
      Mitjans: [
        "titular",
        "article d'opinió",
        "entrevista",
        "emissió",
        "editorial",
        "nota de premsa",
        "audiència",
        "podcast",
        "sindicació",
        "subscripció"
      ],
      "Qüestions socials": [
        "voluntariat",
        "habitatge",
        "immigració",
        "salut pública",
        "accés a l'educació",
        "desigualtat",
        "centre cívic",
        "campanya de fons",
        "sostenibilitat",
        "activisme"
      ],
      Tradicions: [
        "festival de la collita",
        "festa nacional",
        "brindis de boda",
        "dansa folklòrica",
        "cerimònia de fanal",
        "contacontes",
        "cercavila de disfresses",
        "reunió familiar",
        "mercat de temporada",
        "fira d'artesania"
      ]
    },
    C1: {
      "Noms abstractes": [
        "resiliència",
        "integritat",
        "curiositat",
        "compassió",
        "ambigüitat",
        "paradoxa",
        "intuïció",
        "distanciament",
        "ambició",
        "gratitud"
      ],
      Ciència: [
        "genètica",
        "física quàntica",
        "ecosistemes",
        "biologia cel·lular",
        "astronomia",
        "neurociència",
        "termodinàmica",
        "tectònica de plaques",
        "nanotecnologia",
        "evolució"
      ],
      "Moviments artístics": [
        "impressionisme",
        "surrealisme",
        "cubisme",
        "barroc",
        "minimalisme",
        "expressionisme",
        "futurisme",
        "romanticisme",
        "pop art",
        "realisme"
      ],
      Govern: [
        "constitució",
        "parlament",
        "coalició",
        "referèndum",
        "diplomàcia",
        "legislació",
        "jurisdicció",
        "consell de ministres",
        "deure cívic",
        "defensor del poble"
      ],
      Negocis: [
        "part interessada",
        "emprenedoria",
        "estudi de mercat",
        "fidelitat de marca",
        "fusió",
        "diversificació",
        "comparativa",
        "cadena de subministrament",
        "flux de caixa",
        "hub d'innovació"
      ],
      Emocions: [
        "nostàlgia",
        "serenor",
        "anticipació",
        "frustració",
        "fascinació",
        "satisfacció",
        "empatia",
        "alleujament",
        "enveja",
        "admiració"
      ]
    },
    C2: {
      "Expressons idiomàtiques": [
        "trencar el gel",
        "fer públic",
        "anar al gra",
        "més enllà del que és acceptable",
        "de tant en tant",
        "l'última gota",
        "agafar amb pinces",
        "estar indecís",
        "en l'aire",
        "donar en el clau"
      ],
      Filosofia: [
        "existencialisme",
        "estoïcisme",
        "dialèctica",
        "utilitarisme",
        "epistemologia",
        "metafísica",
        "determinisme",
        "fenomenologia",
        "teleologia",
        "ontologia"
      ],
      "Verbs avançats": [
        "scrutar",
        "extrapolar",
        "elucidar",
        "eludir",
        "subratllar",
        "millorar",
        "difondre",
        "corroborar",
        "distingir",
        "encapçalar"
      ],
      "Termes legals": [
        "jurisprudència",
        "precedent",
        "litigi",
        "arbitratge",
        "inhibició",
        "testimoni",
        "responsabilitat",
        "acusació formal",
        "declaració jurada",
        "demandant"
      ],
      "Recursos retòrics": [
        "analogia",
        "metàfora",
        "hipèrbole",
        "al·literació",
        "paradoxa",
        "eufemisme",
        "sinècdoque",
        "ironia",
        "anàfora",
        "oxímoron"
      ],
      "Camps especialitzats": [
        "criptografia",
        "astrofísica",
        "epidemiologia",
        "tipologia lingüística",
        "planificació urbana",
        "enginyeria biomèdica",
        "climatologia",
        "oceanografia",
        "ciència de materials",
        "etnomusicologia"
      ]
    }
  },
  fr: {
    A1: {
      "Objets du quotidien": [
        "livre",
        "chaise",
        "tasse",
        "porte",
        "téléphone",
        "table",
        "cuillère",
        "clé",
        "chemise",
        "sac"
      ],
      Famille: [
        "mère",
        "père",
        "sœur",
        "frère",
        "grand-mère",
        "grand-père",
        "cousin",
        "cousine",
        "tante",
        "oncle"
      ],
      "Nourriture de base": [
        "pain",
        "pomme",
        "lait",
        "riz",
        "fromage",
        "œuf",
        "banane",
        "salade",
        "soupe",
        "jus"
      ],
      "Lieux en ville": [
        "parc",
        "école",
        "banque",
        "supermarché",
        "hôpital",
        "arrêt de bus",
        "bibliothèque",
        "cinéma",
        "restaurant",
        "gare"
      ],
      Classe: [
        "crayon",
        "cahier",
        "tableau",
        "bureau",
        "gomme",
        "carte",
        "sac à dos",
        "marqueur",
        "règle",
        "colle"
      ],
      "Verbes courants": [
        "manger",
        "boire",
        "dormir",
        "lire",
        "écrire",
        "courir",
        "parler",
        "écouter",
        "s'asseoir",
        "se lever"
      ]
    },
    A2: {
      Loisirs: [
        "peinture",
        "jardinage",
        "cyclisme",
        "photographie",
        "cuisine",
        "jouer aux échecs",
        "chanter",
        "danse",
        "camping",
        "pâtisserie"
      ],
      Météo: [
        "ensoleillé",
        "venteux",
        "brumeux",
        "orageux",
        "humide",
        "froid",
        "bruine",
        "canicule",
        "chute de neige",
        "tonnerre"
      ],
      "Voyage essentiel": [
        "passeport",
        "bagage",
        "billet",
        "carte d'embarquement",
        "chambre d'hôtel",
        "carte",
        "souvenir",
        "guide touristique",
        "quai",
        "devise"
      ],
      "Routines quotidiennes": [
        "se réveiller",
        "se brosser les dents",
        "prendre le petit-déjeuner",
        "prendre le bus",
        "étudier",
        "préparer le dîner",
        "faire de l'exercice",
        "faire ses devoirs",
        "regarder la télé",
        "aller se coucher"
      ],
      "Maison et foyer": [
        "lampe",
        "oreiller",
        "miroir",
        "canapé",
        "couverture",
        "rideau",
        "grille-pain",
        "micro-ondes",
        "bouilloire",
        "éponge"
      ],
      Transport: [
        "vélo",
        "métro",
        "tram",
        "moto",
        "trottinette",
        "ferry",
        "calèche",
        "taxi",
        "ceinture de sécurité",
        "plateforme"
      ]
    },
    B1: {
      Technologie: [
        "smartphone",
        "tablette",
        "routeur",
        "chargeur",
        "casque",
        "clavier",
        "microphone",
        "webcam",
        "stockage en nuage",
        "autonomie"
      ],
      Métiers: [
        "ingénieur",
        "journaliste",
        "infirmière",
        "architecte",
        "chimiste",
        "designer",
        "électricien",
        "comptable",
        "bibliothécaire",
        "traducteur"
      ],
      Santé: [
        "mal de tête",
        "mal de gorge",
        "rendez-vous",
        "médicament",
        "allergie",
        "bandage",
        "thermomètre",
        "clinique",
        "programme sportif",
        "premiers secours"
      ],
      "Activités de plein air": [
        "randonnée",
        "kayak",
        "escalade",
        "observation des oiseaux",
        "pique-nique",
        "course en sentier",
        "feu de camp",
        "observation des étoiles",
        "pêche",
        "orientation"
      ],
      Divertissement: [
        "concert",
        "théâtre",
        "exposition",
        "stand-up",
        "comédie musicale",
        "festival",
        "documentaire",
        "court métrage",
        "playlist",
        "série de romans"
      ],
      Shopping: [
        "reçu",
        "remise",
        "cabine d'essayage",
        "caissier",
        "garantie",
        "lèche-vitrine",
        "panier",
        "étiquette de prix",
        "caisse",
        "paquet cadeau"
      ]
    },
    B2: {
      "Matières académiques": [
        "littérature",
        "chimie",
        "économie",
        "philosophie",
        "anthropologie",
        "statistiques",
        "architecture",
        "linguistique",
        "géologie",
        "sociologie"
      ],
      Travail: [
        "date limite",
        "présentation",
        "promotion",
        "mentorat",
        "espace de coworking",
        "appel conférence",
        "entretien annuel",
        "prototype",
        "charge de travail",
        "négociation"
      ],
      Environnement: [
        "recyclage",
        "biodiversité",
        "énergie renouvelable",
        "empreinte carbone",
        "pollution",
        "compost",
        "réserve naturelle",
        "déforestation",
        "courant marin",
        "gaz à effet de serre"
      ],
      Médias: [
        "titre",
        "tribune",
        "entretien",
        "diffusion",
        "éditorial",
        "communiqué de presse",
        "audience",
        "podcast",
        "syndication",
        "abonnement"
      ],
      "Questions sociales": [
        "bénévolat",
        "logement",
        "immigration",
        "santé publique",
        "accès à l'éducation",
        "inégalités",
        "centre communautaire",
        "collecte de fonds",
        "durabilité",
        "activisme"
      ],
      Traditions: [
        "fête des récoltes",
        "jour férié national",
        "toast de mariage",
        "danse folklorique",
        "cérémonie aux lanternes",
        "conte",
        "défilé en costume",
        "réunion de famille",
        "marché saisonnier",
        "foire artisanale"
      ]
    },
    C1: {
      "Noms abstraits": [
        "résilience",
        "intégrité",
        "curiosité",
        "compassion",
        "ambiguïté",
        "paradoxe",
        "intuition",
        "détachement",
        "ambition",
        "gratitude"
      ],
      Science: [
        "génétique",
        "physique quantique",
        "écosystèmes",
        "biologie cellulaire",
        "astronomie",
        "neurosciences",
        "thermodynamique",
        "tectonique des plaques",
        "nanotechnologie",
        "évolution"
      ],
      "Mouvements artistiques": [
        "impressionnisme",
        "surréalisme",
        "cubisme",
        "baroque",
        "minimalisme",
        "expressionnisme",
        "futurisme",
        "romantisme",
        "pop art",
        "réalisme"
      ],
      Gouvernement: [
        "constitution",
        "parlement",
        "coalition",
        "référendum",
        "diplomatie",
        "législation",
        "juridiction",
        "cabinet",
        "devoir civique",
        "médiateur"
      ],
      Affaires: [
        "partie prenante",
        "entrepreneuriat",
        "étude de marché",
        "fidélité à la marque",
        "fusion",
        "diversification",
        "benchmark",
        "chaîne d'approvisionnement",
        "flux de trésorerie",
        "pôle d'innovation"
      ],
      Émotions: [
        "nostalgie",
        "sérénité",
        "anticipation",
        "frustration",
        "admiration",
        "satisfaction",
        "empathie",
        "soulagement",
        "jalousie",
        "émerveillement"
      ]
    },
    C2: {
      "Expressions idiomatiques": [
        "briser la glace",
        "vendre la mèche",
        "aller droit au but",
        "franchir la limite",
        "tous les trente-six du mois",
        "la goutte de trop",
        "prendre avec des pincettes",
        "être partagé",
        "en suspens",
        "mettre le doigt dessus"
      ],
      Philosophie: [
        "existentialisme",
        "stoïcisme",
        "dialectique",
        "utilitarisme",
        "épistémologie",
        "métaphysique",
        "déterminisme",
        "phénoménologie",
        "téléologie",
        "ontologie"
      ],
      "Verbes avancés": [
        "scruter",
        "extrapoler",
        "élucider",
        "contourner",
        "souligner",
        "améliorer",
        "diffuser",
        "corroborer",
        "distinguer",
        "diriger"
      ],
      "Termes juridiques": [
        "jurisprudence",
        "précédent",
        "litige",
        "arbitrage",
        "injonction",
        "témoignage",
        "responsabilité",
        "inculpation",
        "affidavit",
        "demandeur"
      ],
      "Procédés rhétoriques": [
        "analogie",
        "métaphore",
        "hyperbole",
        "allitération",
        "paradoxe",
        "euphémisme",
        "synecdoque",
        "ironie",
        "anaphore",
        "oxymore"
      ],
      "Domaines spécialisés": [
        "cryptographie",
        "astrophysique",
        "épidémiologie",
        "typologie linguistique",
        "urbanisme",
        "ingénierie biomédicale",
        "climatologie",
        "océanographie",
        "science des matériaux",
        "ethnomusicologie"
      ]
    }
  }
};
